apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dr-lab
  labels:
    app: dr-app
type: Opaque
stringData:
  POSTGRES_USER:     dr
  POSTGRES_PASSWORD: drpassword
  POSTGRES_DB:       dr_primary
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: dr-lab
  labels:
    app: minio
type: Opaque
stringData:
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
