apiVersion: 1

datasources:

  - name: Prometheus
    uid: prometheus
    type: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      timeInterval: 5s
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger

  - name: Loki
    uid: loki
    type: loki
    url: http://loki:3100
    access: proxy
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: '"traceID":"(\w+)"'
          url: '$${__value.raw}'
          datasourceUid: jaeger

  - name: Jaeger
    uid: jaeger
    type: jaeger
    url: http://jaeger:16686
    access: proxy
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: '-1m'
        spanEndTimeShift: '1m'
        filterByTraceID: false
        filterBySpanID: false
