apiVersion: v1
kind: Service
metadata:
  name: function-runner
  namespace: faashub
  labels:
    app: function-runner
spec:
  selector:
    app: function-runner
  ports:
  - port: 8002
    targetPort: 8002
    name: http
  type: ClusterIP
