apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: api-gateway
type: Opaque
stringData:
  DATABASE_PASSWORD: "gatewaypass"
  DATABASE_URL: "postgresql://gateway:gatewaypass@postgres:5432/gateway_db"
  JWT_SECRET: "gateway-demo-secret-key-2024"
  POSTGRES_PASSWORD: "gatewaypass"
  POSTGRES_USER: "gateway"
  POSTGRES_DB: "gateway_db"
