apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: chatflow
type: Opaque
# Values are base64-encoded. To decode: echo 'VALUE' | base64 -d
# minioadmin → bWluaW9hZG1pbg==
#
# PRODUCTION NOTE: Use strong, randomly generated keys in real deployments.
# To regenerate:
#   kubectl create secret generic minio-credentials \
#     --namespace chatflow \
#     --from-literal=MINIO_ACCESS_KEY=<key> \
#     --from-literal=MINIO_SECRET_KEY=<secret> \
#     --dry-run=client -o yaml
data:
  MINIO_ACCESS_KEY: bWluaW9hZG1pbg==
  MINIO_SECRET_KEY: bWluaW9hZG1pbg==
