{{- if not .Values.externalSecret.enabled }}
{{/*
  Secret template with optional lookup function support.

  When useLookup is true:
  - If the secret already exists in the cluster, reuse its data
  - If it does not exist, create it from values
  This prevents helm upgrade from overwriting secrets that were
  manually rotated or set by an external process.

  When useLookup is false:
  - Always create/update the secret from values
*/}}
{{- $secretName := printf "%s-credentials" (include "secrets-demo.fullname" .) -}}
{{- $existingSecret := dict -}}
{{- if .Values.secrets.useLookup -}}
  {{- $existingSecret = (lookup "v1" "Secret" .Release.Namespace $secretName) | default dict -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-demo.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
{{- if and .Values.secrets.useLookup (hasKey $existingSecret "data") }}
# Preserving existing secret data (lookup found existing secret)
data:
  DB_USERNAME: {{ index $existingSecret.data "DB_USERNAME" }}
  DB_PASSWORD: {{ index $existingSecret.data "DB_PASSWORD" }}
  API_KEY: {{ index $existingSecret.data "API_KEY" }}
{{- else }}
# Creating secret from values (no existing secret found or lookup disabled)
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  API_KEY: {{ .Values.secrets.apiKey | b64enc | quote }}
{{- end }}
{{- end }}
