apiVersion: v1
kind: Service
metadata:
  name: chat-service
  namespace: chatflow
  labels:
    app: chat-service
    component: application
spec:
  type: ClusterIP
  selector:
    app: chat-service
  ports:
  - port: 8020
    targetPort: 8020
    name: http
