apiVersion: v1
kind: Service
metadata:
  name: file-service
  namespace: chatflow
  labels:
    app: file-service
    component: application
spec:
  type: ClusterIP
  selector:
    app: file-service
  ports:
  - port: 8023
    targetPort: 8023
    name: http
