apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: chatflow
  labels:
    app: frontend
    component: application
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    name: http
