apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: chatflow
  labels:
    app: notification-service
    component: application
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
  - port: 8022
    targetPort: 8022
    name: http
