apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dr-app
  namespace: dr-lab
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: dr-lab.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dr-app
            port:
              number: 4545
