apiVersion: v1
kind: Service
metadata:
  name: postgres-recovery-headless
  namespace: k8s-multi-demo
  labels:
    app: postgres-recovery
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: postgres-recovery
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-recovery
  namespace: k8s-multi-demo
spec:
  serviceName: "postgres-recovery-headless"
  replicas: 2
  selector:
    matchLabels:
      app: postgres-recovery
  template:
    metadata:
      labels:
        app: postgres-recovery
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_DB
          value: "recoverydb"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "testpassword"
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U postgres
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U postgres
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-recovery-service
  namespace: k8s-multi-demo
spec:
  selector:
    app: postgres-recovery
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
---
# ConfigMap for test data initialization
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
  namespace: k8s-multi-demo
data:
  init.sql: |
    CREATE TABLE IF NOT EXISTS recovery_test (
      id SERIAL PRIMARY KEY,
      data TEXT NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
    
    INSERT INTO recovery_test (data) VALUES 
      ('Test data before failure - Entry 1'),
      ('Test data before failure - Entry 2'),
      ('Test data before failure - Entry 3');
    
    CREATE TABLE IF NOT EXISTS cluster_info (
      node_name TEXT PRIMARY KEY,
      last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      status TEXT
    );
---
# Job to initialize test data
apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-data
  namespace: k8s-multi-demo
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: init
        image: postgres:14
        command:
        - /bin/bash
        - -c
        - |
          until pg_isready -h postgres-recovery-0.postgres-recovery-headless -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done
          echo "Postgres is ready, initializing data..."
          psql -h postgres-recovery-0.postgres-recovery-headless -U postgres -d recoverydb << 'EOF'
          CREATE TABLE IF NOT EXISTS recovery_test (
            id SERIAL PRIMARY KEY,
            data TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
          );
          INSERT INTO recovery_test (data) VALUES 
            ('RECOVERY TEST - Data Entry 1'),
            ('RECOVERY TEST - Data Entry 2'),
            ('RECOVERY TEST - Data Entry 3'),
            ('RECOVERY TEST - Critical Data'),
            ('RECOVERY TEST - Must Survive Failure');
          SELECT * FROM recovery_test;
          EOF
          echo "Data initialization complete!"
        env:
        - name: PGPASSWORD
          value: "testpassword"
