# Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-sa
  namespace: scenarios
---
# Role - Namespace-scoped permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demo-role
  namespace: scenarios
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch"]
---
# RoleBinding - Bind Role to ServiceAccount
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demo-binding
  namespace: scenarios
subjects:
- kind: ServiceAccount
  name: demo-sa
  namespace: scenarios
roleRef:
  kind: Role
  name: demo-role
  apiGroup: rbac.authorization.k8s.io
---
# Test Deployment using ServiceAccount
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbac-test-pod
  namespace: scenarios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rbac-test
  template:
    metadata:
      labels:
        app: rbac-test
    spec:
      serviceAccountName: demo-sa
      containers:
      - name: kubectl
        image: bitnami/kubectl:latest
        command: ['sleep', '3600']
