apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  namespace: chatflow
  labels:
    app: file-service
    component: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
        component: application
    spec:
      containers:
      - name: file-service
        # Build: docker build -t chatflow/file-service:v1 app/file-service/
        # Load:  kind load docker-image chatflow/file-service:v1 --name <cluster>
        image: chatflow/file-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8023
          name: http
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-files:5432/files_db"
        - name: MINIO_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: MINIO_ENDPOINT
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_ACCESS_KEY
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-credentials
              key: MINIO_SECRET_KEY
        - name: MINIO_BUCKET
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: MINIO_BUCKET
        - name: PORT
          value: "8023"
        readinessProbe:
          httpGet:
            path: /health
            port: 8023
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8023
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
