apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: chatflow
  labels:
    app: notification-service
    component: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        component: application
    spec:
      containers:
      - name: notification-service
        # Build: docker build -t chatflow/notification-service:v1 app/notification-service/
        # Load:  kind load docker-image chatflow/notification-service:v1 --name <cluster>
        image: chatflow/notification-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8022
          name: http
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-notifications:5432/notifications_db"
        - name: PORT
          value: "8022"
        readinessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8022
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
