apiVersion: apps/v1
kind: Deployment
metadata:
  name: presence-service
  namespace: chatflow
  labels:
    app: presence-service
    component: application
spec:
  replicas: 2
  selector:
    matchLabels:
      app: presence-service
  template:
    metadata:
      labels:
        app: presence-service
        component: application
    spec:
      containers:
      - name: presence-service
        # Build: docker build -t chatflow/presence-service:v1 app/presence-service/
        # Load:  kind load docker-image chatflow/presence-service:v1 --name <cluster>
        image: chatflow/presence-service:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8021
          name: http
        env:
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: service-config
              key: REDIS_URL
        - name: PORT
          value: "8021"
        readinessProbe:
          httpGet:
            path: /health
            port: 8021
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8021
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
