apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: ecommerce
  labels:
    app: inventory-service
spec:
  selector:
    app: inventory-service
  ports:
  - name: http
    port: 8005
    targetPort: 8005
  type: ClusterIP
