apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: chatflow
  labels:
    app: redis
    component: infrastructure
spec:
  serviceName: redis
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        component: infrastructure
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        # Disable persistence — chat messages are durably stored in PostgreSQL;
        # Redis is used only for pub/sub fan-out and TTL-based presence keys.
        command: ["redis-server", "--save", "", "--appendonly", "no"]
        ports:
        - containerPort: 6379
          name: redis
        readinessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        livenessProbe:
          exec:
            command: ["redis-cli", "ping"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
# Headless service — gives stable DNS: redis-0.redis.chatflow.svc.cluster.local
# Apps connect via: redis://redis:6379
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chatflow
  labels:
    app: redis
    component: infrastructure
spec:
  clusterIP: None   # Headless — required for StatefulSet DNS
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
