apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sc10-frontend
  namespace: argocd
spec:
  project: team-frontend
  source:
    repoURL: https://github.com/shaydevops2024/kubernetes-production-simulator.git
    targetRevision: HEAD
    path: argocd-scenarios/10-projects-rbac/manifests/frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-sc-10-fe
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
