apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-backend
  namespace: argocd
spec:
  description: Backend team project - restricted to backend namespace
  sourceRepos:
    - 'https://github.com/shaydevops2024/kubernetes-production-simulator.git'
  destinations:
    - namespace: argocd-sc-10-be
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: ''
      kind: '*'
    - group: 'apps'
      kind: '*'
