# existing-service.yaml
# This represents a service deployed manually with kubectl.
# It has NO Helm annotations or labels -- it is not managed by Helm.
apiVersion: v1
kind: Service
metadata:
  name: adopted-app
  namespace: helm-scenarios
  labels:
    app: adopted-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: adopted-app
