apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: api-gateway
  labels:
    app: analytics-service
    project: gatewayhub
spec:
  type: ClusterIP
  selector:
    app: analytics-service
  ports:
    - name: http
      port: 8002
      targetPort: 8002
      protocol: TCP
