apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-gateway
  labels:
    app: api-service
    project: gatewayhub
spec:
  type: ClusterIP
  selector:
    app: api-service
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      protocol: TCP
