apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: api-gateway
  labels:
    app: postgres
    project: gatewayhub
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
