# k8s-scenarios/07-pod-disruption-budget/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-demo
  namespace: scenarios
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: pdb-demo
