"""ObserveApp — Observability Demo Application

A FastAPI application that simulates a SaaS analytics platform.
It is instrumented with:
  - Prometheus metrics (HTTP request count/latency + custom business metrics)
  - OpenTelemetry distributed tracing (exports to Jaeger/Tempo via OTLP)
  - Structured JSON logging (compatible with Loki/Promtail)

Your job is NOT to write this application — it's already done.
Your job is to instrument and observe it using the tools in this project.
"""

import asyncio
import os
import random
import time
import uuid
from collections import deque
from contextlib import asynccontextmanager
from datetime import datetime, timezone

import uvicorn
from fastapi import FastAPI, Request, Response
from fastapi.responses import HTMLResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

# ── Prometheus metrics ─────────────────────────────────────────────────────────
from prometheus_client import (
    Counter,
    Gauge,
    Histogram,
    Info,
    CONTENT_TYPE_LATEST,
    generate_latest,
)

HTTP_REQUESTS = Counter(
    "http_requests_total",
    "Total HTTP requests processed",
    ["method", "path", "status"],
)
HTTP_LATENCY = Histogram(
    "http_request_duration_seconds",
    "HTTP request latency in seconds",
    ["method", "path"],
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0],
)
ACTIVE_SESSIONS = Gauge("app_active_sessions", "Number of active user sessions")
EVENTS_TRACKED = Counter(
    "app_events_tracked_total",
    "Analytics events ingested by type",
    ["event_type"],
)
REPORTS_GENERATED = Counter(
    "app_reports_generated_total",
    "Reports generated by status",
    ["status"],
)
REPORT_DURATION = Histogram(
    "app_report_generation_seconds",
    "Time to generate a report in seconds",
    buckets=[0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0],
)
QUEUE_DEPTH = Gauge("app_queue_depth", "Number of items waiting in the processing queue")
APP_INFO = Info("observe_app", "Application metadata")
APP_INFO.info({"version": "1.0.0", "environment": os.getenv("ENVIRONMENT", "local")})

# ── Structured JSON logging ────────────────────────────────────────────────────
import logging

_memory_logs: deque = deque(maxlen=100)


class _MemoryHandler(logging.Handler):
    """Keeps recent log entries in memory so the UI can display them."""

    def emit(self, record: logging.LogRecord) -> None:
        try:
            entry: dict = {
                "timestamp": datetime.now(timezone.utc).isoformat(),
                "level": record.levelname,
                "message": record.getMessage(),
            }
            for key in (
                "request_id",
                "endpoint",
                "method",
                "status",
                "duration_ms",
                "event_type",
                "report_type",
                "error",
            ):
                if hasattr(record, key):
                    entry[key] = getattr(record, key)
            _memory_logs.appendleft(entry)
        except Exception:
            pass


def _setup_logging() -> logging.Logger:
    root = logging.getLogger()
    root.setLevel(logging.INFO)
    stdout_handler = logging.StreamHandler()
    try:
        from pythonjsonlogger import jsonlogger

        formatter = jsonlogger.JsonFormatter(
            fmt="%(asctime)s %(levelname)s %(name)s %(message)s",
            rename_fields={"asctime": "timestamp", "levelname": "level"},
        )
        stdout_handler.setFormatter(formatter)
    except ImportError:
        pass
    root.handlers = [stdout_handler, _MemoryHandler()]
    return logging.getLogger("observe-app")


log = _setup_logging()

# ── OpenTelemetry tracing (optional) ──────────────────────────────────────────
def _setup_tracing(app: "FastAPI") -> None:
    endpoint = os.getenv("OTLP_ENDPOINT", "")
    if not endpoint:
        log.info("Tracing disabled — set OTLP_ENDPOINT to enable")
        return
    try:
        from opentelemetry import trace
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor
        from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor

        resource = Resource.create(
            {
                "service.name": "observe-app",
                "service.version": "1.0.0",
                "deployment.environment": os.getenv("ENVIRONMENT", "local"),
            }
        )
        provider = TracerProvider(resource=resource)
        provider.add_span_processor(
            BatchSpanProcessor(OTLPSpanExporter(endpoint=f"{endpoint}/v1/traces"))
        )
        trace.set_tracer_provider(provider)
        FastAPIInstrumentor.instrument_app(app)
        log.info("Tracing enabled", extra={"otlp_endpoint": endpoint})
    except Exception as exc:
        log.warning(f"Could not initialise tracing: {exc}")


# ── Simulation state ───────────────────────────────────────────────────────────
_sim: dict = {"error_mode": False, "slow_mode": False, "high_traffic": False}


# ── Background activity simulator ─────────────────────────────────────────────
async def _background_activity() -> None:
    """Produces a realistic stream of metrics and logs without any real traffic."""
    while True:
        try:
            # Drift active sessions toward a target
            target = (
                random.randint(80, 300) if _sim["high_traffic"] else random.randint(20, 80)
            )
            current = ACTIVE_SESSIONS._value.get()
            ACTIVE_SESSIONS.set(round(current + (target - current) * 0.15))

            # Analytics events
            event_types = ["page_view", "button_click", "form_submit", "api_call", "error_thrown"]
            weights = (
                [0.15, 0.10, 0.05, 0.15, 0.55]
                if _sim["error_mode"]
                else [0.40, 0.25, 0.12, 0.18, 0.05]
            )
            for _ in range(random.randint(2, 8 if _sim["high_traffic"] else 4)):
                et = random.choices(event_types, weights=weights)[0]
                EVENTS_TRACKED.labels(event_type=et).inc()

            # Queue depth
            delta = (
                random.randint(-2, 6) if _sim["high_traffic"] else random.randint(-3, 2)
            )
            QUEUE_DEPTH.set(max(0, QUEUE_DEPTH._value.get() + delta))

            # Occasional report generation
            if random.random() < 0.08:
                duration = (
                    random.uniform(3.0, 10.0) if _sim["slow_mode"] else random.uniform(0.05, 1.5)
                )
                status = (
                    "error" if _sim["error_mode"] and random.random() < 0.45 else "success"
                )
                REPORTS_GENERATED.labels(status=status).inc()
                REPORT_DURATION.observe(duration)
                log.info(
                    "report generated",
                    extra={
                        "report_type": random.choice(["daily", "weekly", "custom", "realtime"]),
                        "duration_ms": round(duration * 1000),
                        "status": status,
                    },
                )

        except Exception as exc:
            log.error(f"Background task error: {exc}")

        await asyncio.sleep(2)


# ── App lifecycle ──────────────────────────────────────────────────────────────
@asynccontextmanager
async def _lifespan(app: "FastAPI"):
    _setup_tracing(app)
    log.info("ObserveApp started", extra={"version": "1.0.0", "port": 8000})
    ACTIVE_SESSIONS.set(42)
    task = asyncio.create_task(_background_activity())
    yield
    task.cancel()
    log.info("ObserveApp stopped")


app = FastAPI(
    title="ObserveApp",
    version="1.0.0",
    lifespan=_lifespan,
    docs_url="/docs",
)

app.mount("/static", StaticFiles(directory="static"), name="static")

# ── Request instrumentation middleware ────────────────────────────────────────
_SKIP_PATHS = {"/metrics", "/health", "/favicon.ico"}


@app.middleware("http")
async def _instrument(request: Request, call_next):
    if request.url.path in _SKIP_PATHS or request.url.path.startswith("/static"):
        return await call_next(request)

    start = time.perf_counter()
    req_id = uuid.uuid4().hex[:8]
    path = request.url.path

    # Simulate slowdown
    if _sim["slow_mode"] and not path.startswith("/api/simulate"):
        await asyncio.sleep(random.uniform(0.8, 3.0))

    # Inject synthetic errors
    if (
        _sim["error_mode"]
        and not path.startswith("/api/simulate")
        and random.random() < 0.3
    ):
        duration = time.perf_counter() - start
        HTTP_REQUESTS.labels(method=request.method, path=path, status="500").inc()
        HTTP_LATENCY.labels(method=request.method, path=path).observe(duration)
        log.error(
            "request failed",
            extra={
                "request_id": req_id,
                "method": request.method,
                "path": path,
                "status": 500,
            },
        )
        return JSONResponse(
            status_code=500,
            content={"error": "Internal Server Error (simulated)", "request_id": req_id},
        )

    response = await call_next(request)
    duration = time.perf_counter() - start

    HTTP_REQUESTS.labels(
        method=request.method, path=path, status=str(response.status_code)
    ).inc()
    HTTP_LATENCY.labels(method=request.method, path=path).observe(duration)

    log.info(
        "request completed",
        extra={
            "request_id": req_id,
            "method": request.method,
            "path": path,
            "status": response.status_code,
            "duration_ms": round(duration * 1000, 1),
        },
    )
    return response


# ── Routes ─────────────────────────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
async def index():
    with open("static/index.html") as f:
        return f.read()


@app.get("/metrics")
async def metrics():
    return Response(generate_latest(), media_type=CONTENT_TYPE_LATEST)


@app.get("/health")
async def health():
    return {
        "status": "healthy",
        "version": "1.0.0",
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.get("/api/stats")
async def stats():
    return {
        "active_sessions": round(ACTIVE_SESSIONS._value.get()),
        "queue_depth": int(QUEUE_DEPTH._value.get()),
        "simulation": dict(_sim),
        "recent_logs": list(_memory_logs)[:20],
        "timestamp": datetime.now(timezone.utc).isoformat(),
    }


@app.post("/api/track")
async def track(event_type: str = "page_view"):
    rid = uuid.uuid4().hex[:8]
    EVENTS_TRACKED.labels(event_type=event_type).inc()
    log.info("event tracked", extra={"request_id": rid, "event_type": event_type})
    return {"ok": True, "request_id": rid, "event_type": event_type}


@app.post("/api/report")
async def generate_report(report_type: str = "daily"):
    rid = uuid.uuid4().hex[:8]
    start = time.perf_counter()
    duration = (
        random.uniform(3.0, 8.0) if _sim["slow_mode"] else random.uniform(0.1, 1.2)
    )
    await asyncio.sleep(min(duration, 3.0))
    elapsed = time.perf_counter() - start
    status = "error" if _sim["error_mode"] and random.random() < 0.5 else "success"
    REPORTS_GENERATED.labels(status=status).inc()
    REPORT_DURATION.observe(elapsed)
    log.info(
        "report generated via API",
        extra={
            "request_id": rid,
            "report_type": report_type,
            "status": status,
            "duration_ms": round(elapsed * 1000),
        },
    )
    if status == "error":
        return JSONResponse(
            status_code=500,
            content={"error": "Report failed (simulated)", "request_id": rid},
        )
    return {
        "report_id": rid,
        "type": report_type,
        "status": status,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "duration_ms": round(elapsed * 1000),
    }


# ── Simulation control endpoints ───────────────────────────────────────────────
@app.post("/api/simulate/errors")
async def toggle_errors():
    _sim["error_mode"] = not _sim["error_mode"]
    state = "enabled" if _sim["error_mode"] else "disabled"
    log.warning(f"error simulation {state}")
    return {"error_mode": _sim["error_mode"], "message": f"Error simulation {state}"}


@app.post("/api/simulate/slowdown")
async def toggle_slowdown():
    _sim["slow_mode"] = not _sim["slow_mode"]
    state = "enabled" if _sim["slow_mode"] else "disabled"
    log.warning(f"slowdown simulation {state}")
    return {"slow_mode": _sim["slow_mode"], "message": f"Slow mode {state}"}


@app.post("/api/simulate/traffic")
async def toggle_traffic():
    _sim["high_traffic"] = not _sim["high_traffic"]
    state = "enabled" if _sim["high_traffic"] else "disabled"
    log.info(f"high traffic simulation {state}")
    return {"high_traffic": _sim["high_traffic"], "message": f"High traffic {state}"}


@app.post("/api/simulate/reset")
async def reset():
    _sim.update({"error_mode": False, "slow_mode": False, "high_traffic": False})
    log.info("simulation reset")
    return {"message": "All simulations reset", "simulation": dict(_sim)}


if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=False)
