# k8s-scenarios/17-high-availability-special/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ha-demo-pdb
  namespace: scenarios
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: ha-demo
